# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from collections import deque

# 1️⃣ Fila de produtos (entrada por ordem de chegada)
fila_produtos = deque()
fila_produtos.append({"nome": "Tênis de Corrida Nike", "estoque": 5})
fila_produtos.append({"nome": "Camiseta Adidas", "estoque": 3})
fila_produtos.append({"nome": "Bola de Futebol Penalty", "estoque": 4})

# 2️⃣ Fila de pedidos
fila_pedidos = deque()
fila_pedidos.append({"cliente": "João", "quantidade": 1})
fila_pedidos.append({"cliente": "Maria", "quantidade": 2})
fila_pedidos.append({"cliente": "Ana", "quantidade": 1})
fila_pedidos.append({"cliente": "Carlos", "quantidade": 2})
fila_pedidos.append({"cliente": "Laura", "quantidade": 3})

# 3️⃣ Processar os pedidos
while fila_pedidos and fila_produtos:
    pedido = fila_pedidos.popleft()
    quantidade = pedido["quantidade"]
    cliente = pedido["cliente"]

    while quantidade > 0 and fila_produtos:
        produto = fila_produtos[0]  # pega o primeiro produto da fila

        if produto["estoque"] >= quantidade:
            produto["estoque"] -= quantidade
            print(f"{cliente} comprou {quantidade}x {produto['nome']}. Estoque restante: {produto['estoque']}")
            if produto["estoque"] == 0:
                fila_produtos.popleft()  # remove da fila se acabou o estoque
            quantidade = 0  # pedido totalmente atendido

        else:
            print(f"{cliente} comprou {produto['estoque']}x {produto['nome']} (estoque esgotado)")
            quantidade -= produto["estoque"]
            fila_produtos.popleft()  # remove produto esgotado

    if quantidade > 0:
        print(f"{cliente} ficou com {quantidade} produto(s) pendente(s) por falta de estoque.\n")