# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import ipywidgets as widgets
from IPython.display import display, clear_output

metodos_pagamento = {
    'PIX': [
        ('Chave PIX', 'text', ''),
        ('Tipo de chave', 'dropdown', ['CPF', 'CNPJ', 'Email', 'Telefone', 'Aleatória'])
    ],
    'Cartão de Crédito': [
        ('Número do cartão', 'text', '0000 0000 0000 0000'),
        ('Nome no cartão', 'text', ''),
        ('Validade (MM/AA)', 'text', 'MM/AA'),
        ('CVV', 'password', '123')
    ],
    'Boleto Bancário': [
        ('Nome completo', 'text', ''),
        ('CPF', 'text', ''),
        ('Rua', 'textarea', ''),
        ('Número', 'textarea', ''),
        ('Bairro', 'textarea', ''),
        ('Cidade', 'textarea', ''),
        ('UF', 'textarea', '')
    ]
}

def criar_widgets(campos):
    lista_widgets = []
    for label, tipo, padrao in campos:
        lista_widgets.append(widgets.Label(label))
        if tipo == 'text':
            lista_widgets.append(widgets.Text(value=padrao))
        elif tipo == 'password':
            lista_widgets.append(widgets.Password(value=padrao))
        elif tipo == 'dropdown':
            lista_widgets.append(widgets.Dropdown(options=padrao))
        elif tipo == 'textarea':
            lista_widgets.append(widgets.Textarea(value=padrao))
    return widgets.VBox(lista_widgets)

dropdown_metodo = widgets.Dropdown(
    options=list(metodos_pagamento.keys()),
    description='Pagamento:',
    value=None,
    style={'description_width': 'initial'}
)

formulario_output = widgets.Output()

def atualizar_formulario(change):
    with formulario_output:
        clear_output()
        metodo = change['new']
        if metodo:
            campos = metodos_pagamento[metodo]
            box = criar_widgets(campos)
            display(box)

dropdown_metodo.observe(atualizar_formulario, names='value')

display(dropdown_metodo, formulario_output)