# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hO8VvITmrqWmef01jr4DQ8J7Itce7xoJ
"""

class Usuario:
    def __init__(self, nome):
        self.nome = nome
        self.enderecos = []

    def adicionar_endereco(self, endereco):
        if len(self.enderecos) >= 3:
            removido = self.enderecos.pop()
            print(f"Limite de 3 endereços atingido. Endereço removido: {removido}")
        self.enderecos.append(endereco)
        print(f"Endereço adicionado: {endereco}")

    def listar_enderecos(self):
        print(f"\nEndereços do usuário {self.nome}:")
        for i, endereco in enumerate(self.enderecos, 1):
            print(f"{i}. {endereco}")



usuario = Usuario("João")
usuario.adicionar_endereco("Rua A, 123")
usuario.adicionar_endereco("Rua B, 456")
usuario.adicionar_endereco("Rua C, 789")
usuario.listar_enderecos()
usuario.adicionar_endereco("Rua D, 000")
usuario.listar_enderecos()