# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dmU4qVgKfLh9BfbvNMwvlU30epFBBomd
"""

usuarios_logados = [ ]


def login(usuario):
    usuarios_logados.append(usuario)
    print(f"Usuário '{usuario}' logado.")


def logout():
    if usuarios_logados:
        usuario = usuarios_logados.pop()
        print(f"Usuário '{usuario}' deslogado.")
    else:
        print("Nenhum usuário logado.")

def usuario_ativo():
    if usuarios_logados:
        print(f"Usuário ativo: {usuarios_logados[-1]}")
    else:
        print("Nenhum usuário logado.")

login("jose_silva")
login("maria_oliveira")
usuario_ativo()
logout()
usuario_ativo()