# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hbowF76pS9snLGpaBaiLc4-Bg-wW8Eeb
"""

carrinho = []

def adicionar_item(nome, quantidade, preco):
    carrinho.append([nome, quantidade, preco])
    print(" {nome} adicionado ao carrinho.")

def remover_item(nome):
    for item in carrinho:
        if item[0].lower() == nome.lower():
            carrinho.remove(item)
            print(" {nome} removido do carrinho.")
            return
    print("Item não encontrado.")

def mostrar_carrinho():
    if not carrinho:
        print(" Carrinho vazio.")
        return

    print("\n--- Carrinho de Compras ---")
    for i, item in enumerate(carrinho, 1):
        nome, qtd, preco = item
        print(f"{i}. {nome} - {qtd} x R${preco:.2f} = R${qtd * preco:.2f}")
    print("Total:" f" R${calcular_total():.2f}")

def calcular_total():
    total = 0
    for item in carrinho:
        total += item[1] * item[2]
    return total

def menu():
    while True:
        print("\n1. Adicionar item")
        print("2. Remover item")
        print("3. Mostrar carrinho")
        print("4. Sair")
        opcao = input("Escolha uma opção: ")

        if opcao == "1":
            nome = input("Nome do produto: ")
            qtd = int(input("Quantidade: "))
            preco = float(input("Preço unitário: R$"))
            adicionar_item(nome, qtd, preco)
        elif opcao == "2":
            nome = input("Nome do produto para remover: ")
            remover_item(nome)
        elif opcao == "3":
            mostrar_carrinho()
        elif opcao == "4":
            print("Saindo...")
            break
        else:
            print("Opção inválida.")

menu()

